name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
  pages: write
  id-token: write
  checks: write
jobs:
  compile:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - uses: cachix/cachix-action@v12
      with:
        name: potsdam-pnp
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Compile LaTeX document
      run: nix build --option log-lines 300 --no-update-lock-file
    - name: Archive cards.pdf
      uses: actions/upload-artifact@v3
      with:
        name: cards
        path: result/
    - name: Archive compile logs
      uses: actions/upload-artifact@v3
      with:
        name: compile-log
        path: result/cards.log
    - name: Github page
      run: nix build .#website --option log-lines 300 -o _site --no-update-lock-file
    - uses: actions/upload-pages-artifact@v2
  gh-pages:
    name: Deploy website
    uses: ./.github/workflows/deploy-gh-pages.yml
    needs: compile
  checks:
    uses: ./.github/workflows/latex-compile-check.yml
    needs: compile