name: 'compile'
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
  pages: write
  id-token: write
  checks: write
jobs:
  compile:
    name: Generate cards.pdf
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - name: Compile LaTeX document
      run: nix build
    - name: Archive cards.pdf
      uses: actions/upload-artifact@v3
      with:
        name: cards
        path: result/
    - name: Show cards.log
      run: cat result/cards.log
    - name: Archive compile logs
      uses: actions/upload-artifact@v3
      with:
        name: compile-log
        path: result/cards.log
  gh-pages:
    name: Generate website
    uses: ./.github/workflows/gh-pages.yml
    needs: compile
  checks:
    uses: ./.github/workflows/latex-compile-check.yml
    needs: compile