name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
  pages: write
  id-token: write
  checks: write
jobs:
  compile:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: "log-lines = 300"
    - uses: cachix/cachix-action@v12
      with:
        name: potsdam-pnp
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Compile LaTeX document
      run: nix build --no-update-lock-file
    - name: Archive cards.pdf
      uses: actions/upload-artifact@v3
      with:
        name: cards
        path: result/
    - name: Latex check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SHA: ${{ github.event.pull_request.head.sha || github.sha }}
      run: nix run .#latex-check --no-update-lock-file -- result/cards.log
    - name: Github page
      run: nix build .#website -o _site --no-update-lock-file
    - uses: actions/upload-pages-artifact@v2
  gh-pages:
    name: Deploy website
    uses: ./.github/workflows/deploy-gh-pages.yml
    needs: compile
